<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Cheetah</title>
	<link rel="stylesheet" href="/assets/css/main.css">
	<link rel="stylesheet" href="/assets/css/bootstrap/bootstrap.min.css">
	<link rel="stylesheet" href="/assets/css/bootstrap/bootstrap.css">
	<link rel="stylesheet" href="/assets/font/fontawesome-webfont.ttf">
	<link rel="stylesheet" href="/assets/pwa/manifest.json">
	<script src="/assets/pwa/pwabuilder-sw.js"></script>
	<script src="/assets/js/jquery-3.4.1.min.js"></script>
	<script src="/assets/js/bootstrap/bootstrap.min.js"></script>
	<script src="/assets/js/bootstrap/bootstrap.js"></script>
</head>
<body>
	<!-- Tag de impressão do PHP. Vai servir como renderizador do Layout Principal... Neste caso estará a chamar o conteúdo do 'index.phtml'-->
	<?= $this->content() ?> 
</body>
</html>